# Generated by Django 5.0.8 on 2024-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
